name: test
on:
  push:
    branches:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtest-tcp-perl libcache-memcached-perl memcached

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: test
        run: |
          go install github.com/kazebur/wsgate-server/cmd/wsgate-server@latest
          make check
          make
          make proccheck
        env:
          CGO_ENABLED: 0

      - name: Snapshot GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: build --snapshot
